const { google } = require('googleapis');
const logger = require('./logger'); // Assuming logger.js is in the same directory and exports logger

// Environment variables should be set for these.
const ANDROID_PACKAGE_NAME = process.env.ANDROID_PACKAGE_NAME || 'com.example.biometricvotingapp';
// GOOGLE_APPLICATION_CREDENTIALS should be set in the environment pointing to the service account key JSON file.

let playIntegrityClientInstance; // Renamed to avoid confusion with the google.playintegrity function itself

/**
 * Initializes the Google Play Integrity API client.
 * Uses Application Default Credentials (ADC) by checking GOOGLE_APPLICATION_CREDENTIALS.
 */
function initializeClient() {
    if (playIntegrityClientInstance) {
        return playIntegrityClientInstance;
    }
    try {
        const auth = new google.auth.GoogleAuth({
            scopes: ['https.www.googleapis.com/auth/playintegrity']
            // GOOGLE_APPLICATION_CREDENTIALS environment variable will be used by default if set.
        });

        // The auth object itself can be used for making authenticated requests with the API client.
        playIntegrityClientInstance = google.playintegrity({
            version: 'v1',
            auth: auth // Pass the auth object explicitly
        });

        logger.info('Google Play Integrity API client initialized successfully.');
        return playIntegrityClientInstance;
    } catch (error) {
        logger.error('Failed to initialize Google Play Integrity API client (ensure GOOGLE_APPLICATION_CREDENTIALS is set for your service account):', error.message);
        // For security, avoid logging the full error object in production if it might contain sensitive details.
        // In dev, error.stack might be useful.
        throw new Error('PlayIntegrityClientInitError: Could not initialize Play Integrity API client. Ensure GOOGLE_APPLICATION_CREDENTIALS is set correctly for your service account that has Play Integrity API enabled.');
    }
}

/**
 * Verifies a Play Integrity token.
 * @param {string} token The Play Integrity token string from the client.
 * @param {string} clientNonce The nonce the client used to request the token. This nonce is generated by the client.
 * @returns {Promise<{isValid: boolean, verdicts: object | null, error: string | null, details: object | null}>}
 */
async function verifyToken(token, clientNonce) {
    if (!token) {
        logger.warn('Play Integrity: Verification attempt with missing token.');
        return { isValid: false, verdicts: null, error: 'Integrity token is missing.', details: null };
    }
    if (!clientNonce) {
        // While the server doesn't strictly need the clientNonce for decodeIntegrityToken,
        // it's crucial for the server to compare it with the nonce inside the decoded token's requestDetails.
        logger.warn('Play Integrity: Verification attempt with missing client-provided nonce.');
        return { isValid: false, verdicts: null, error: 'Client nonce is missing for verification.', details: null };
    }

    const client = initializeClient(); // Ensures client is initialized
    // If initializeClient() throws, this function will also throw, handled by caller.

    try {
        logger.info(`Play Integrity: Verifying token. Client Nonce (first 10): ${clientNonce ? clientNonce.substring(0,10) : 'N/A'}...`);
        const response = await client.decodeIntegrityToken({
            packageName: ANDROID_PACKAGE_NAME,
            // The 'decodeIntegrityTokenRequest' object is not needed at the top level.
            // The 'integrityToken' field is directly under the main request object.
            // This was a slight misinterpretation of the googleapis client library structure in the prompt.
            // Correct structure for the request body for decodeIntegrityToken:
            requestBody: { // The body of the request for this method
                 integrityToken: token,
            }
        });

        // For debugging, log the structure of response.data if needed:
        // logger.debug('Play Integrity API raw response data:', JSON.stringify(response.data, null, 2));

        const payload = response.data.tokenPayloadExternal;
        if (!payload) {
            logger.warn('Play Integrity: No tokenPayloadExternal in Play Integrity response.');
            return { isValid: false, verdicts: null, error: 'Invalid Play Integrity API response: Missing token payload.', details: response.data };
        }

        // 1. Verify Nonce
        if (!payload.requestDetails || payload.requestDetails.nonce !== clientNonce) {
            logger.warn(`Play Integrity: Nonce mismatch. Expected (client-provided): ${clientNonce}, Got from token: ${payload.requestDetails ? payload.requestDetails.nonce : 'N/A'}`);
            return { isValid: false, verdicts: payload, error: 'Nonce mismatch. This could indicate a replay attack.', details: payload };
        }
        logger.info('Play Integrity: Nonce verified successfully.');

        // 2. Check Device Integrity Verdict
        const deviceIntegrity = payload.deviceIntegrity || {};
        let meetsRequiredDeviceIntegrity = false;
        if (deviceIntegrity.deviceRecognitionVerdict &&
            (deviceIntegrity.deviceRecognitionVerdict.includes('MEETS_DEVICE_INTEGRITY') ||
             deviceIntegrity.deviceRecognitionVerdict.includes('MEETS_BASIC_INTEGRITY'))) {
            meetsRequiredDeviceIntegrity = true;
        }

        if (!meetsRequiredDeviceIntegrity) {
            logger.warn('Play Integrity: Device does not meet required integrity level.', { verdicts: deviceIntegrity.deviceRecognitionVerdict });
            return { isValid: false, verdicts: payload, error: 'Device integrity check failed.', details: payload };
        }
        logger.info(`Play Integrity: Device integrity met required level. Verdicts: ${deviceIntegrity.deviceRecognitionVerdict.join(', ')}`);

        // 3. Check App Integrity
        const appIntegrity = payload.appIntegrity || {};
        if (appIntegrity.appRecognitionVerdict !== 'PLAY_RECOGNIZED') {
            // Allowing 'UNRECOGNIZED_VERSION' can be a policy decision. For high security, might restrict to 'PLAY_RECOGNIZED'.
            // If allowing UNRECOGNIZED_VERSION, ensure other checks (like package name from token) are robust.
            logger.warn(`Play Integrity: App integrity check failed or version unrecognized. Verdict: ${appIntegrity.appRecognitionVerdict}`);
            // Depending on policy, this might not be a fatal error, but for voting, it's a strong indicator of risk.
            return { isValid: false, verdicts: payload, error: 'App integrity check failed (not recognized by Play).', details: payload };
        }
        logger.info(`Play Integrity: App integrity verified. Verdict: ${appIntegrity.appRecognitionVerdict}`);

        // 4. Check Licensing (Optional, based on app type)
        const accountDetails = payload.accountDetails || {};
        if (accountDetails.appLicensingVerdict !== 'LICENSED') {
            logger.warn(`Play Integrity: App licensing check failed. Verdict: ${accountDetails.appLicensingVerdict}`);
            // For a free voting app, 'UNLICENSED' might be acceptable if app is distributed outside Play Store,
            // but if it's strictly Play Store distributed, 'LICENSED' is expected.
            // This is not necessarily a failure for vote validity unless policy dictates.
        } else {
            logger.info('Play Integrity: App licensing verified.');
        }

        // All critical checks passed
        logger.info('Play Integrity: Token verification successful for all critical checks.');
        return {
            isValid: true,
            verdicts: { // Return selected parts of the payload for the caller to use if needed
                requestDetailsNonce: payload.requestDetails ? payload.requestDetails.nonce : null,
                appRecognitionVerdict: appIntegrity.appRecognitionVerdict,
                deviceRecognitionVerdict: deviceIntegrity.deviceRecognitionVerdict,
                appLicensingVerdict: accountDetails.appLicensingVerdict
            },
            error: null,
            details: null // No need to return full payload if structured verdicts are provided
        };

    } catch (error) {
        // Log detailed error for server-side debugging
        const errorMessage = error.response && error.response.data && error.response.data.error && error.response.data.error.message
                           ? error.response.data.error.message
                           : error.message;
        logger.error('Play Integrity: Error verifying token with Google API.', {
            message: errorMessage,
            status: error.response ? error.response.status : null,
            data: error.response ? error.response.data : null,
            // stack: error.stack // Potentially too verbose for prod logs, but good for debug
        });

        let userFriendlyError = 'Failed to verify app integrity with Google due to a server-side issue.';
        if (error.code && (error.code === 401 || error.code === 403)) {
            userFriendlyError = 'Failed to verify app integrity: Authentication or permission error with Google API. Check service account and API key settings.';
        } else if (error.code && error.code >= 500) {
            userFriendlyError = 'Failed to verify app integrity: Google services temporarily unavailable. Please try again later.';
        }

        return { isValid: false, verdicts: null, error: userFriendlyError, details: error.response ? error.response.data : null };
    }
}

module.exports = {
    // initializeClient, // Not typically needed to export if lazily initialized on first verifyToken call
    verifyToken,
};

// No need to call initializeClient() on module load if it's called within verifyToken.
// This ensures it's only initialized if/when needed and handles potential errors at call time.
```
